### ISSUE TITLE
无法在任务中配置当期SS活动关卡名进行作战

### ISSUE THREAD

**Issue by siuze** [MaaAssistantArknights/maa-cli#128]
在任务列表中填写银心湖列车SS的关卡“RS-5”后无法正常执行作战任务，会被直接跳过，没有错误信息输出。    
任务配置：    
```
tasks:
  - type: StartUp
    params:
      client_type: Official
      start_game_enabled: true

  - type: Fight
    strategy: first
    params:
    variants:
      - params:
          stage: Annihilation
          expiring_medicine: 1000
          times: 5
        condition:
          type: Combined
          conditions:
            - type: Weekday
              weekdays:
                - Mon
            - type: Time
              end: 12:00:00
      - params:
          stage: RS-5
          expiring_medicine: 1000

  - type: CloseDown

```

使用版本：
```
2023-12-11 16:22:21 Up to date: MaaCore v4.27.1.
2023-12-11 16:22:26 Up to date: maa-cli v0.4.0-alpha.1702239035.
```

运行输出：
```
root@NAS:/volume1/maa# maa run daily -v
2023-12-11 16:36:21 Connected
2023-12-11 16:36:31 StartTask StartUp
2023-12-11 16:36:37 CompleteTask StartUp
2023-12-11 16:36:38 StartTask Award
2023-12-11 16:36:43 CompleteTask Award
2023-12-11 16:36:44 AllTasksCompleted
```
把RS-5改成1-7是可以正常作战的，1-7作战日志如下：   
```
root@NAS:/volume1/maa# maa run daily -v
2023-12-11 16:31:52 Connected
2023-12-11 16:32:00 StartTask StartUp
[INFO] /home/runner/work/MaaDeps/MaaDeps/vcpkg/buildtrees/maa-fastdeploy/src/7b46ddfce2-ca3f4b205b.clean/fastdeploy/runtime.cc(544)::Init       Runtime initialized with Backend::ORT in Device::CPU.
[INFO] /home/runner/work/MaaDeps/MaaDeps/vcpkg/buildtrees/maa-fastdeploy/src/7b46ddfce2-ca3f4b205b.clean/fastdeploy/runtime.cc(544)::Init       Runtime initialized with Backend::ORT in Device::CPU.
libpng warning: sBIT: invalid
2023-12-11 16:32:17 CompleteTask StartUp
2023-12-11 16:32:17 StartTask Fight
[INFO] /home/runner/work/MaaDeps/MaaDeps/vcpkg/buildtrees/maa-fastdeploy/src/7b46ddfce2-ca3f4b205b.clean/fastdeploy/runtime.cc(544)::Init       Runtime initialized with Backend::ORT in Device::CPU.
[INFO] /home/runner/work/MaaDeps/MaaDeps/vcpkg/buildtrees/maa-fastdeploy/src/7b46ddfce2-ca3f4b205b.clean/fastdeploy/runtime.cc(544)::Init       Runtime initialized with Backend::ORT in Device::CPU.
2023-12-11 16:32:33 MissionStart 1 times
2023-12-11 16:35:09 Drops Unknown: 12 (+12), 酮凝集: 1 (+1), 固源岩: 1 (+1), 龙门币: 144 (+144)
2023-12-11 16:35:33 CompleteTask Fight
2023-12-11 16:35:33 StartTask Award
^CError: Interrupted by user!
```

是哪里没更新吗？

**Comment by siuze** [comment]
另外maa-core的版本是选择了beta更新通道的：
```
[core]
channel = "beta"
```
改成alpha后尝试更新maa-core会报如下错误：
```
 root@NAS:/volume1/maa# maa update
2023-12-11 16:15:37 Fetching MaaCore version info (channel: alpha)...
2023-12-11 16:15:37 Found newer MaaCore version: v4.28.0-beta.1.d043.g5caa2bea3 (current: v4.27.1)
Error: Asset not found
```
会是这里的问题吗？  
另外有办法配置maa-cli的更新通道吗？

**Comment by wangl-cc** [comment]
RS-5 的导航的资源 MaaCore 那边没有 release，所以没有办法导航。我正在实现热更新，等热更新弄好了就可以在获得 RS-5 的导航了。CLI 的更新通道可以在 cli.toml 里面设置 `[cli.channel]`，相关的文档我还没更新，最新的配置文件怎么填，可以去看 `config_examples`。

**Comment by wangl-cc** [comment]
Core 没办法更新 `alpha` 是因为只编译了 Windows版，不过 `MaaCore` 的 `beta` 最新版不是 `v4.28.0-beta.1` 吗，里面有 RS-6,7,8的导航。

**Comment by siuze** [comment]
了解了，感谢大佬的无私付出。   
   
   
另外也期待后期能实现更加的详细和易于解析的输出日志，或者直接有一个任务总结？
比如：
```
2023/12/11 17:39 任务【daily】报表
[启动] 耗时 1 min
--------------------
[公招] 耗时 3 min
公招发起： ★★★ 群攻, 近战位
公招发起： ★★★★ 快速复活
公招开包：★★★ 梓兰
公招开包：★★★ 安德切尔
---------------------------
[基建] 耗时 10 min
 制造站(赤金) 进驻 XXX XXX XXX
 制造站(赤金) 进驻 XXX XXX XXX
 制造站(经验) 进驻 XXX XXX XXX
 制造站(源石) 进驻 XXX XXX XXX
贸易站(龙门币) 进驻 XXX XXX
贸易站(源石) 进驻 XXX XXX
会客室 进驻 XXX XXX
...
---------------------------
[作战] 耗时 20 min
RS-5 * 4次 掉落 驮兽盲盒*12, 酮凝集*1, 固源岩*1 , 龙门币*144
1-7 * 2次 掉落 XXXXXXXXXXXXX
-----------------------
[信用商店] 耗时 3 min
购入 招聘许可、固源岩、装置、龙门币
-----------------------
[奖励] 耗时 2min
邮件收取 合成玉*20
每日任务 已全部完成
每周任务 已全部完成


```

**Comment by siuze** [comment]
> Core 没办法更新 `alpha` 是因为 `MaaRelease` 那边只上传了了 Windows 版的 `alpha`，不过 `MaaCore` 的 `beta` 最新版不是 `v4.28.0-beta.1` 吗，里面有 RS-6,7,8 的导航。

我也觉得奇怪，但是配置为beta它还是升不上去：
```
root@NAS:/volume1/maa# maa update
2023-12-11 17:55:39 Fetching MaaCore version info (channel: beta)...
2023-12-11 17:55:40 Up to date: MaaCore v4.27.1.
```

**Comment by wangl-cc** [comment]
> 了解了，感谢大佬的无私付出。
> 
> 另外也期待后期能实现更加的详细和易于解析的输出日志，或者直接有一个任务总结？ 比如：
> 
> ```
> 2023/12/11 17:39 任务【daily】报表
> [启动] 耗时 1 min
> --------------------
> [公招] 耗时 3 min
> 公招发起： ★★★ 群攻, 近战位
> 公招发起： ★★★★ 快速复活
> 公招开包：★★★ 梓兰
> 公招开包：★★★ 安德切尔
> ---------------------------
> [基建] 耗时 10 min
>  制造站(赤金) 进驻 XXX XXX XXX
>  制造站(赤金) 进驻 XXX XXX XXX
>  制造站(经验) 进驻 XXX XXX XXX
>  制造站(源石) 进驻 XXX XXX XXX
> 贸易站(龙门币) 进驻 XXX XXX
> 贸易站(源石) 进驻 XXX XXX
> 会客室 进驻 XXX XXX
> ...
> ---------------------------
> [作战] 耗时 20 min
> RS-5 * 4次 掉落 驮兽盲盒*12, 酮凝集*1, 固源岩*1 , 龙门币*144
> 1-7 * 2次 掉落 XXXXXXXXXXXXX
> -----------------------
> [信用商店] 耗时 3 min
> 购入 招聘许可、固源岩、装置、龙门币
> -----------------------
> [奖励] 耗时 2min
> 邮件收取 合成玉*20
> 每日任务 已全部完成
> 每周任务 已全部完成
> ```

这个可以，等有时间了实现一下。

> > Core 没办法更新 `alpha` 是因为 `MaaRelease` 那边只上传了了 Windows 版的 `alpha`，不过 `MaaCore` 的 `beta` 最新版不是 `v4.28.0-beta.1` 吗，里面有 RS-6,7,8 的导航。
> 
> 我也觉得奇怪，但是配置为beta它还是升不上去：
> 
> ```
> root@NAS:/volume1/maa# maa update
> 2023-12-11 17:55:39 Fetching MaaCore version info (channel: beta)...
> 2023-12-11 17:55:40 Up to date: MaaCore v4.27.1.
> ```

我看了一下，不知道为什么，MaaRelease 那边的被降版本了，https://github.com/MaaAssistantArknights/MaaRelease/commit/0e19e0506b2063f03e224a796168025c3abfcbfa#diff-6aa9ae853f00afc0790b6a447de47eaa721d8577882f7a9d7a55134e16f07fbdL2.

**Comment by wangl-cc** [comment]
`MaaCore` 准备发 `beta.2`，等 beta.2 发了，应该就可以更新了。

> 另外也期待后期能实现更加的详细和易于解析的输出日志，或者直接有一个任务总结？

这个你可以单独发个 feature request 的 issue 吗?

**Comment by siuze** [comment]
> `MaaCore` 准备发 `beta.2`，等 beta.2 发了，应该就可以更新了。
> 
> > 另外也期待后期能实现更加的详细和易于解析的输出日志，或者直接有一个任务总结？
> 
> 这个你可以单独发个 feature request 的 issue 吗?

好的

**Comment by wangl-cc** [comment]
MaaCore 那边已经发了新的 Beta 了，资源更新也弄好了。这个 issue 就先关了。
