### ISSUE TITLE
对于大陆地区用户，可以将默认资源更新上游仓库设置为`git.maa-org.net`

### ISSUE THREAD

**Issue by Cryolitia** [MaaAssistantArknights/maa-cli#138]
https://git.maa-org.net/MAA/MaaResource

由 @ChingCdesu 提供维护及稳定性保证。

亦有助于评估使用git进行资源热更新对CDN的请求压力

**Comment by wangl-cc** [comment]
应该怎么判断是中国大陆？还是直接把默认地址改成这个？

**Comment by Cryolitia** [comment]
简单粗暴的话可以判断系统时区，然后在多写点注释和文档让用户可以自己改

**Comment by wangl-cc** [comment]
相比时区可能用 Locale 来判断会更准确一点 （虽然我自己的 Locale 都不是 ZH-CN)，我去研究一下怎么跨平台读取 Locale。

**Comment by wangl-cc** [comment]
这个网站好像挂了，仓库看不到也pull不下来。

**Comment by Cryolitia** [comment]
> 这个网站好像挂了，仓库看不到也pull不下来。

CC @ChingCdesu 咋回事

**Comment by Cryolitia** [comment]
已恢复
