### ISSUE TITLE
在运行前打印活动内容

### ISSUE THREAD

**Issue by Cryolitia** [MaaAssistantArknights/maa-cli#139]
https://github.com/MaaAssistantArknights/MaaResource/blob/main/cache/gui/StageActivity.json

**Comment by wangl-cc** [comment]
读取这个很容易，但是我不确定改怎么时候打印出来，这个可能需要一个全局的客户端选项。具体的 stage 信息应该怎么用，输入stage 的可选项？

**Comment by Cryolitia** [comment]
单独加一个 `maa info` 的命令（？，或者在 `maa run`之前打印
