### ISSUE TITLE
Aur中的maa-cli包未启用core_installer特性

### ISSUE THREAD

**Issue by sss20081** [MaaAssistantArknights/maa-cli#187]
Aur中的maa-cli包未启用core_installer特性，导致无法使用maa install 和maa update命令，只能安装Aur中的另一个包maa-assistant-arknights或maa-assistant-arknights-bin,以下是打包的maa-cli的PKGBUILD
![图片](https://github.com/MaaAssistantArknights/maa-cli/assets/62577592/e7db6a27-1881-4221-b01c-1af6fd1b3d88)

**Comment by wangl-cc** [comment]
CC: @horror-proton

**Comment by horror-proton** [comment]
fixed in https://github.com/archlinux/aur/commit/e7c596f07f6e153af4df9956c4fecea51666eed1

cargo 好像不能只排除一个 feature, 有点难受 (
