### ISSUE TITLE
Check `config::task::condition::tests::active::time` fails at midnight

### ISSUE THREAD

**Issue by horror-proton** [MaaAssistantArknights/maa-cli#188]
If cargo test was runned between 23:50:00 and +1 00:10:00, assertion
https://github.com/MaaAssistantArknights/maa-cli/blob/0b70be90d3cabb07ad1e9a191a91a8686638c243/maa-cli/src/config/task/condition.rs#L200-L204
would fail.
```
now_datetime =         00:05:07.980003710
now_datetime - 10min = 23:55:07.980003710
now_datetime + 10min = 00:15:07.980003710
```
perhaps date was not compared here

**Comment by wangl-cc** [comment]
I believe the test for time, rather than date-time, will break at midnight.
