### ISSUE TITLE
在macos下 maa-cli 启动的游戏无法正常代理作战

### ISSUE THREAD

**Issue by zzj0311** [MaaAssistantArknights/maa-cli#202]
复现方法: 使用 maa-cli 配置task startup start_game_enable＝true 此时运行 maa－cli 稳定复现 
＊ 代理作战时弹战斗记录失效
＊ 肉鸽时报400错误

此时 手动重启客户端 可以正常进行代理，关闭客户端后使用maamacui启动 可以正常执行代理作战 关闭客户端后再次尝试使用maa－cli启动 上述问题复现

运行环境： mac mini m2 playcover 官服

**Comment by wangl-cc** [comment]
我知道这个bug，在终端启动 PlayCover 下的游戏会这样，比如你直接 `open -a 明日方舟` 或者到游戏的文件夹里面手动运行 `arknights` 都会这样，甚至通过 `open -a PlayCover` 启动 PlayCover， 然后在PlayCover里面手动点击打开游戏都会这样。然而如果这个命令不是从终端启动的，比如在快捷指令里运行 shell 脚本运行 maa，或者在 crontab 的定时任务里运行 maa 都是正常的。我不知道这个 bug 究竟是什么引起，所以我一直没有解决。目前来说如果你想定时运行，应该是可以正常使用的，但是如果你是交互使用，那么你可能需要手动启动游戏或者用 MAA GUI。

**Comment by zzj0311** [comment]
那么神奇 crontab没问题倒也没事了 :)

**Comment by wangl-cc** [comment]
因为这个问题还没有解决，所以我先把这个 issue 打开。一方面作为一个记录，另一方面也方便其他遇到相同问题的人查看。

**Comment by wangl-cc** [comment]
我测试了一下，似乎在最新版本已经修复了。
