### ISSUE TITLE
Linux系统下的默认connection config有误

### ISSUE THREAD

**Issue by starrin** [MaaAssistantArknights/maa-cli#209]
https://github.com/MaaAssistantArknights/maa-cli/blob/6d8f2f1244410a8e031cd22cd70326f9c1ca104a/maa-cli/src/config/asst.rs#L188-L196
在Linux系统下connection config应为CompatPOSIXShell，而不是CompatLinux

**Comment by wangl-cc** [comment]
可能之前不小心改错了，现在已经修复，并且加上测试了。
