### ISSUE TITLE
生息演算功能错误

### ISSUE THREAD

**Issue by dragove** [MaaAssistantArknights/maa-cli#222]
maa-cli v0.4.4
MaaCore v5.2.0-beta.2

任务配置
`rec.toml`
```toml
[[tasks]]
type = "ReclamationAlgorithm"
[tasks.params]
mode = 1
```

启动命令 `maa run rec`

运行结果：
成功进入到了生息演算内，但是一进图就报错推出

错误信息：

```
[2024-03-09 16:00:52 ERROR] ReclamationAlgorithm Error
Summary
----------------------------------------
[ReclamationAlgorithm] 15:59:49 - 16:00:52 (1m 2s) Error
Error: Some error occurred during running task!

```

**Comment by hzxjy1** [comment]
根据 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/8190 的描述，问题可能出现在新版的生息演算是通过自定义命令(Custom)运行的，maa core尚未实现新版生息演算的接口。
以及，从更新日志上看，新版生息演算还未实现刷赤金的模式。

**Comment by hzxjy1** [comment]
我改了一下maa下载包里附带的python脚本，替换同名文件后更改adb配置应该就可以用了
主要代码是这个：
```python
    asst.append_task('Custom', {
        'enable': True,
        'task_names': [
        "Reclamation2"
        ]
    })
```
下周末有空的话我试试能不能整合进maacli去@wangl-cc
[sample.zip](https://github.com/MaaAssistantArknights/maa-cli/files/14547295/sample.zip)

**Comment by wangl-cc** [comment]
直接用 `ReclamationAlgorithm` 任务应该是可行的，因为他会自动使用自定义任务 `Reclamation2` MaaAssistantArknights/MaaAssistantArknights#8229。不过 `mode` 确实是不支持的，但是这个应该不影响。因为生息演算我是自己打的，maa 好像是要从头开始，我怕 maa 给我存档删了所以我一直没有测试。可以看一下 core 那边的 `asst.log` 吗？

**Comment by dragove** [comment]
[asst.log](https://github.com/MaaAssistantArknights/maa-cli/files/14548772/asst.log)

尝试去掉 mode 确实还是这样的错误

用 python 脚本有同样的错误。看着是需要一份作业文件？文档中没找到怎么用。

**Comment by hzxjy1** [comment]
问题可能出现在你进关卡的时候队伍里带了人导致无法退出关卡

**Comment by dragove** [comment]
还真是，自己开一局删掉编队内的干员后能用了。没想到还有这个限制，是不是因为少了一个“确认不携带干员“的弹窗导致的。这个问题和 maa-cli 无关，所以我关了。

**Comment by hzxjy1** [comment]
是少了这个弹窗，看看后续更新能不能解决吧
