### ISSUE TITLE
运行时出现神秘日志

### ISSUE THREAD

**Issue by Eletary** [MaaAssistantArknights/maa-cli#227]
```
❯ maa run u
[2024-03-13 17:11:20 INFO ] Connected
[2024-03-13 17:11:21 INFO ] FastestWayToScreencap RawByNc 123
[2024-03-13 17:11:21 INFO ] StartUp Start
[2024-03-13 17:11:24 INFO ] StartUp Completed
[2024-03-13 17:11:24 INFO ] Recruit Start
[WARNING] /home/runner/work/MaaDeps/MaaDeps/vcpkg/buildtrees/maa-fastdeploy/src/7b46ddfce2-ca3f4b205b.clean/fastdeploy/runtime.cc(246)::UseGpu    The FastDeploy didn't compile with GPU, will force to use CPU.
[INFO] /home/runner/work/MaaDeps/MaaDeps/vcpkg/buildtrees/maa-fastdeploy/src/7b46ddfce2-ca3f4b205b.clean/fastdeploy/runtime.cc(544)::Init Runtime initialized with Backend::ORT in Device::CPU.
[INFO] /home/runner/work/MaaDeps/MaaDeps/vcpkg/buildtrees/maa-fastdeploy/src/7b46ddfce2-ca3f4b205b.clean/fastdeploy/runtime.cc(544)::Init Runtime initialized with Backend::ORT in Device::CPU.
[2024-03-13 17:11:28 INFO ] Recruit Completed
[2024-03-13 17:11:28 INFO ] Infrast Start
[2024-03-13 17:11:39 INFO ] EnterFacility
……
```
中间这段日志不像是由 cli 正常产生。请问有没有办法关闭或重定向。

该问题在运行任何任务时均出现。

**Comment by wangl-cc** [comment]
这是 [fastdeploy](https://github.com/MaaAssistantArknights/FastDeploy) 的日志，是 MaaCore 依赖的一个库。它加载的时候就会有这个提示，在新版本的其实可以通过编译时不开启 PRINT_LOG 去掉 https://github.com/MaaAssistantArknights/FastDeploy/pull/4, 但是 core 那边用的还是旧版，所以会有这个信息，也没有办法在运行的时候去掉。不知道，你是在什么平台使用，如果是 macOS 可以用 HomeBrew 装，Arch Linux 可以装 [AUR 的包](https://aur.archlinux.org/packages/maa-cli)，nix 也有一个[NUR 包](https://github.com/Cryolitia/nur-packages/tree/master/pkgs/MaaAssistantArknights)，但是我没用 nix 所以不知道怎么用。这三个包管理器的装的就是最新版的 core，不过要配合包管理器装的 cli 才能正常找到资源。

> The FastDeploy didn't compile with GPU, will force to use CPU.

这个是你设置了使用 GPU 吗，直接下载的 core 里面的 fastdeploy 没有编译 GPU 支持。AUR 和 NUR 的包可以选有 CUDA 支持的。

**Comment by Eletary** [comment]
我没有设置任何GPU相关内容。

我去测试一下 AUR 包，谢谢。

**Comment by wangl-cc** [comment]
这个 issue 我已经把它放进常见问题了，就先关掉了。如果你测试有任何问题，欢迎再打开。
