### ISSUE TITLE
可以添加musl的静态编译版本吗？

### ISSUE THREAD

**Issue by CoronaAustralis** [MaaAssistantArknights/maa-cli#261]
我尝试把maa-cli放进alpine镜像中，但是由于他需要一些libc的链接库，所以使用不了，我尝试apk add gcompat, glibc ,但是并没有什么卵用，所以能否添加一个静态编译的版本。

**Comment by wangl-cc** [comment]
maa-cli 的 musl 编译应该问题不大，但是 Core 那边也没有 musl 版本吧，Core 在 Alpine Linux 下可以用吗？

**Comment by CoronaAustralis** [comment]
> maa-cli 的 musl 编译应该问题不大，但是 Core 那边也没有 musl 版本吧，Core 在 Alpine 下可以用吗？

刚刚试了下，core好像还真不行，那只有用标准libc镜像了。

**Comment by wangl-cc** [comment]
cli 可以编译成功，但是不能加载 Core，不知道是因为下载的 core 时 glibc 编译的还是因为什么。
