### ISSUE TITLE
Error when running "maa hot-update": No such file or directory (os error 2)

### ISSUE THREAD

**Issue by 050644zf** [MaaAssistantArknights/maa-cli#278]
OS: Arch Linux, running on Userland application on an Android device
Arch: aarch64

I'm using compiled version of maa-cli downloaded from github release and put it under the `/usr/local/bin`, the MaaCore was successfully installed but the MaaResource failed to clone with the following output:

```
[userland@localhost ~]$ maa hot-update -vvvv     
[2024-04-25 09:00:56 DEBUG] Cloning resource repository...
Error: Failed to clone resource repository

Caused by:
    No such file or directory (os error 2)
```

I managed to install the AUR package version and it worked fine, but to install AUR package in userland version of archlinux required quite long time.

**Comment by wangl-cc** [comment]
Which backend do you used to clone resource repository? The default backend uses git in your system. Try `libgit2`, if it not in your system.

https://github.com/MaaAssistantArknights/maa-cli/blob/main/maa-cli/docs/en-US/config.md#cli-related-configurations

**Comment by 050644zf** [comment]
got it, it's git issue, thx

i think the prompt here should be improved like  "maybe 'git' wasn't installed correctly".

**Comment by Cryolitia** [comment]
it's wired, AUR is using libgit2, and it does have libgit2 in dependencies.

Are we talking about https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=maa-cli or other package(?

**Comment by 050644zf** [comment]
> it's wired, AUR is using libgit2, and it does have libgit2 in dependencies.
> 
> Are we talking about https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=maa-cli or other package(?

Nah i was referring AUR packages just cuz it work fine there. Not related to issue.
