### ISSUE TITLE
需要更新git2的版本

### ISSUE THREAD

**Issue by hzxjy1** [MaaAssistantArknights/maa-cli#283]
在Archlinux中libgit2.so的版本过新，导致maa-cli出现以下报错：
```
maa: error while loading shared libraries: libgit2.so.1.7: cannot open shared object file: No such file or directory
```
需要``` maa-cli/Cargo.toml```中的git2版本更新至最新的```0.18.3```

**Comment by wangl-cc** [comment]
Lock 里面的就是 0.18.3：

https://github.com/MaaAssistantArknights/maa-cli/blob/d7b20842347b9835a540e6ce66d7bd5e8d8e4424/Cargo.lock#L584-L597

**Comment by hzxjy1** [comment]
刚刚试了以下Cargo.toml没有问题，估计是Aur的源还没更新
