### ISSUE TITLE
macOS 动态链接库无法加载

### ISSUE THREAD

**Issue by hguandl** [MaaAssistantArknights/maa-cli#295]
当前预编译版本的 maa-cli 在运行时会出现链接库错误：
```
dyld: Library not loaded: /opt/homebrew/opt/libgit2/lib/libgit2.1.7.dylib
```
原因是 Homebrew 的 libgit2 近期更新了版本至 2.1.8，dylib 的文件名发生了改变。

对于这个问题有两个方案：
1. 定时检查依赖的 libgit2 和 openssl 版本，在 Homebrew 更新后尽快重新编译以更新路径。
2. 使用以上两个库的 vendor feature，让 `maa` 实现 self-contained。经测试，二进制文件大小由 5MB 增长为 12MB。

**Comment by wangl-cc** [comment]
Github Release 里面的应该就是 self-contained 的。你是指 Homebrew 预编译的 maa-cli 吗？这个确实是一个问题，虽然 self-contained 不太符合 Homebrew 的方针，但是反正这个 formula 也不是在 homebrew-core 里，确实可以考虑也使用 vendors openssl 和 libgit2。

**Comment by wangl-cc** [comment]
https://github.com/MaaAssistantArknights/homebrew-tap/pull/205 我已经重新触发了一次编译，现在应该没有问题了。

**Comment by wangl-cc** [comment]
我看了一下 openssl 的链接目标 /opt/homebrew/opt/openssl@3/lib/libssl.3.dylib，所以不会因为更新出问题。只需要 libgit2 不用 Homebrew 的就好了。
