### ISSUE TITLE
显示找不到资源路径

### ISSUE THREAD

**Issue by AndyYang12345** [MaaAssistantArknights/maa-cli#297]
本人ubuntu22.04系统 使用redroid模拟安卓设备 adb能够正常连接容器 但不清楚maa有没有连接上 再就是使用maa fight的时候显示找不到资源路径（见附件截图） 实在不知道是什么问题 劳烦开发者替我看看问题所在
另 一开始有两条warning 显示找不到hotupdate 文件夹 但是我用hot-update命令解决了
开发文档上标注了maa update可以下载资源 但maa和maa-cli都已经更新到了最新版本了（见附件） 仍无法解决上述问题

```
harekasa@harekasa-desktop:~$ sudo maa fight 1-7
[2024-07-30 19:04:46 WARN ] Resource directory not found!
Error: Failed to load MaaCore!

Caused by:
    0: Failed to load MaaCore!
    1: libMaaCore.so: cannot open shared object file: No such file or directory`

harekasa@harekasa-desktop:~$ maa version
maa-cli v0.4.8
MaaCore v5.5.0

harekasa@harekasa-desktop:~$ maa init --force
Whether to setup connection [Y/n]:
1. MuMuPro
2. PlayCover
3. ADB [default]
Please select connection preset (empty for default):
Please input adb path [default: adb]:
Please input address to connect [default: auto]: 5555
Please input configuration name to connect (auto for most cases) [default: auto]:
Whether to setup instance options [Y/n]:
Whether to enable ADB Lite (a lightweight ADB implementation) [y/N]:
Whether to deploy operator with pause [y/N]:
Whether to kill ADB server on exit [y/N]:
1. ADB (most compatible but slow)
2. MiniTouch (faster but may not work on some devices)
3. MaaTouch (rewrite of MiniTouch, fast and compatible with most devices) [default]
4. MacPlayTools (this if and only if you are connecting to PlayCover)
Please select touch mode (empty for default):
Whether to setup resource configurations (don't setup it for most cases) [y/N]: y
1. None (no global resource needed by Official and BiliBili client) [default]
2. YostarJP (resource fror Japenese client)
3. YostarKR (resource for Korean client)
4. YostarEN (resource for English client)
5. Txwy (resource for Traditional Chinese client)
Please select global resource to load (empty for default):
1. None (no platform different resource needed by Android client) [default]
2. iOS (resource for PlayCover which run iOS client on macOS)
Please select platform different resource to load (empty for default):
Whether to load custom resource from user configuration directory [y/N]:
Whether to setup static options (for hardware acceleration) [y/N]:
```

**Comment by wangl-cc** [comment]
能看一下资源和数据文件夹的情况吗：

```bash
ls "$(maa dir data)"
ls "$(maa dir resource)"
```

**Comment by AndyYang12345** [comment]
`harekasa@harekasa-desktop:~$ ls "$(maa dir data)"
lib  MaaResource  resource
harekasa@harekasa-desktop:~$ ls "$(maa dir resource)"
Arknights-Tile-Pos  global           onnx              roguelike
battle_data.json    infrast.json     PaddleCharOCR     stages.json
config.json         item_index.json  PaddleOCR         tasks.json
copilot             minitouch        platform_diff     template
custom_infrast      ocr_config.json  recruitment.json  version.json
`

**Comment by AndyYang12345** [comment]
<img width="436" alt="屏幕截图 2024-07-31 095941" src="https://github.com/user-attachments/assets/2c58c3d2-8a29-4ad1-bb23-6da71fe9f621">

**Comment by wangl-cc** [comment]
那应该没有问题呀，都安装好了。`maa version` 可以显示 Core 版本号，那 Core 就装好了。`maa dir resource` 也可以找到资源那说明资源也装好了。按理来说运行应该没有问题。

**Comment by AndyYang12345** [comment]
可是还是运行不起来啊啊啊 这样下去我只能转战maax了

**Comment by wangl-cc** [comment]
maa run 不要带 sudo

**Comment by AndyYang12345** [comment]
哦有道理诶 但是我一开始用普通用户权限运行的时候 汇报一长串的错 说无法截图之类的 然后就想着用root去执行了
这么想来应该是没有连上adb的原因之类的吧
有什么解决方案吗 需要报错的截图吗

**Comment by wangl-cc** [comment]
> 汇报一长串的错 说无法截图之类的

无法截图有可能和 ADB 没连上有关，也可能和 TouchMode 有关。你再试一次 

```
maa fight 1-7 -vv
```

然后发一下命令的输出。然后发一下你的配置文件 `"(maa dir config)/profiles/default.toml"` 和 core 的日志文件 `"(maa dir log)/asst.log".

**Comment by AndyYang12345** [comment]
![defalt](https://github.com/user-attachments/assets/610866ac-30c7-4ac7-9079-9039af09cbad)
![log](https://github.com/user-attachments/assets/d0ce5241-1585-4b35-ad8a-363746489784)

asst.log 太大了不知道怎么发 我是linux新人 反正是用tail看了后面100来行 截了个图
命令的输出结果也截图发过来了
defalt也是 希望对您的分析有帮助
![screencap_fail](https://github.com/user-attachments/assets/895ec1ba-2bb4-4998-8188-5a74dd5cc066)
![screencap_fail2](https://github.com/user-attachments/assets/54112378-edba-4408-be53-51af2c4ded4e)

**Comment by AndyYang12345** [comment]
主要是maa在树莓派上而我用的ssh 不方便传文件 如果你还需要的话请再来找我要log文件 我试着发过来

**Comment by wangl-cc** [comment]
address 应该是应该是一个完整的地址而不是只有端口，比如如果 maa 和 redroid 在同一个机器上的话，这个地址可能是`127.0.0.0:5555`。

**Comment by AndyYang12345** [comment]
用init更改了连接端口显示能够连接上了 但是还是出现战斗失败的提示
![new_log](https://github.com/user-attachments/assets/5b7b256d-302a-42ba-85c4-01f79f0f0e10)

**Comment by wangl-cc** [comment]
游戏正常打开了吗？`maa fight 1-7` 只有进入游戏了才行。如果游戏没有打开，对于官服可以用 `maa startup Official` 来启动游戏。

**Comment by AndyYang12345** [comment]
![error](https://github.com/user-attachments/assets/0c3fbb92-928e-4eae-8ced-229f5d652994)
我仍然会有maa无法打开对应关卡的问题 并且还有如图的不断报错 maa似乎想打开1-7 但总是卡在奇怪的位置

**Comment by AndyYang12345** [comment]
抱歉可能需要等明天下午夏活版本更新后才有时间上传log

**Comment by wangl-cc** [comment]
上述报错是 onnxruntime 的编译问题，可能在 https://github.com/MaaAssistantArknights/MaaDeps/pull/24 修复了。打不开 1-7 可能是识别问题，也可能是 TouchMode 的问题，需要看 log 才能确定。

**Comment by AndyYang12345** [comment]
关于onnxruntime的问题可以进一步说明一下吗 我不是很清楚如何修复这一问题 现在正在测试肉鸽代理 希望一会儿就能够上传我的log

**Comment by wangl-cc** [comment]
那个报错目前不影响使用，是 onnxruntime 编译的问题，需要等 Core 更新或者不使用官方编译的包。我建议你暂时无视这些报错，等更新，如果你非要解决可以考虑装 Homebrew 或者 Nix 的包。

**Comment by wangl-cc** [comment]
onnxruntime 的问题已经被修复了，这个 issue 我就先关了，如果有任何问题，欢迎 reopen。
