### ISSUE TITLE
热更新资源镜像是弃用了吗？

### ISSUE THREAD

**Issue by starrin** [MaaAssistantArknights/maa-cli#306]
[https://git.maa-org.net/MAA/MaaResource](https://git.maa-org.net/MAA/MaaResource)
最近几天这个地址好像404了

**Comment by wangl-cc** [comment]
我也不是很清楚，我不是镜像的维护者。Windows GUI 那边已经停了资源热更新，MAA 之后要重构资源热更新，git 的方案不在考虑范围。等最终方案确定了，到时候 CLI 也会跟进，应该就不用这个了。目前的话，如果能连 GitHub 的话，还是直接用 GitHub 的仓库吧。

**Comment by starrin** [comment]
好的，就是想确认一下
主要是我用来跑maa的服务器没法直连github，我自己搞个镜像先用着
