### ISSUE TITLE
MaaCore配置中instance_options.touchMode值的问题

### ISSUE THREAD

**Issue by BoredTape** [MaaAssistantArknights/maa-cli#307]
[官网文档](https://maa.plus/docs/zh-cn/manual/cli/config.html)中使用"MAATouch"
![1](https://github.com/user-attachments/assets/d3acd657-113d-4ef7-9f85-90c22604ca7f)

[代码schema](https://github.com/MaaAssistantArknights/maa-cli/blob/bfe51f07e4968e55bedec9f13d0d791acc649e15/maa-cli/schemas/asst.schema.json#L80)中使用"MaaTouch"
![2](https://github.com/user-attachments/assets/46a732e0-1340-4764-850a-25b2b7e73c09)

以哪个为准？

**Comment by wangl-cc** [comment]
两者都可以。

**Comment by BoredTape** [comment]
ok，谢谢。目前我正在为maa-cli开发一个简易的ui，方便在linux及mac os上使用（maaX貌似在短期内不会更新）maa-cli对于非编程人员使用门槛相对高了些，希望简易ui能降低maa-cli的使用门槛
