### ISSUE TITLE
无法正常运行 maa install 和 maa update

### ISSUE THREAD

**Issue by Hapenia-Lans** [MaaAssistantArknights/maa-cli#310]
使用 cargo 安装的 maa-cli.
运行下面 `maa update` 的输出
```
PS C:\Users\hapen> maa update
Fetching MaaCore version info (channel: stable)...
Up to date: MaaCore v5.5.11452.
Cloning into 'C:\Users\hapen\AppData\Roaming\loong\maa\data\MaaResource'...
remote: 404 page not found
fatal: repository 'https://git.maa-org.net/MAA/MaaResource.git/' not found
Error: Failed to clone resource repository

Caused by:
    Command failed
```

实测使用浏览器打开 https://git.maa-org.net/MAA/MaaResource.git/ 的结果是404 page not found.

**Comment by wangl-cc** [comment]
似乎 <https://git.maa-org.net/MAA/MaaResource.git/> 最近都打不开，你可以在 cli 配置文件里面改一下链接，如果你可以连上 GitHub 就用 <https://github.com/MaaAssistantArknights/MaaResource.git>。如果确认弃用了的话，我会在下个版本更改默认值。
