### ISSUE TITLE
奇怪的报错

### ISSUE THREAD

**Issue by tsctsc6** [MaaAssistantArknights/maa-cli#333]
![image](https://github.com/user-attachments/assets/5aed6015-a814-4bff-99b5-578f2226a027)

如上图所示，每次启动会报这些错误，下面还有很多类似的。但是仔细一看这些错误信息，说“想要在位置a注册某个东西，但是已经在位置a注册过了”。有点让人无语。是不是重复引用文件之类的？

其实不影响正常使用，只是这种报错信息会很多，刷屏，看着不舒服。

**Comment by wangl-cc** [comment]
这是一个已知问题 https://github.com/MaaAssistantArknights/maa-cli/issues/288, https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9618, 这个问题是 MaaCore 带的 onnxruntime 编译有问题导致导致的, 在 https://github.com/MaaAssistantArknights/MaaAssistantArknights/pull/10268 已经获得了修复。但是由于 Windows 用户几乎全都是用的 GUI，看不到这些报错，所以为了缓解更新服务器的压力，Windows 上暂时并没有更新这个修复。如果你想修复这个问题，可以考虑下载这个包https://github.com/MaaAssistantArknights/MaaDeps/releases/download/2024-08-17/MaaDeps-x64-windows-runtime.tar.xz，然后用里面的 onnxruntime_maa.dll 替换到 maa-cli 装的对应文件，这个文件的位置可以通过 maa dir lib 获得。

**Comment by tsctsc6** [comment]
好的，谢谢
