### ISSUE TITLE
maa install 报错

### ISSUE THREAD

**Issue by dragove** [MaaAssistantArknights/maa-cli#35]
操作系统：Arch Linux
glibc: 2.38-3

`file maa`

```
maa: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=772cd007cd3a66a684c8226359183710265564d9, for GNU/Linux 3.2.0, with debug_info, not stripped
```

Installing package (channel: stable)...
Speed test for mirrors...
Error: request or response body error: error reading a body from connection: cannot decrypt peer's message

我的网络应该是正常的

**Comment by wangl-cc** [comment]
我在阿里云的Ubuntu上下载没问题呀，你试试直接下载这几个连接试试？
```
        "mirrors": [
          "https://s3.maa-org.net:25240/maa-release/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.23.3/MAA-v4.23.3-linux-x86_64.tar.gz",
          "https://agent.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.23.3/MAA-v4.23.3-linux-x86_64.tar.gz",
          "https://maa.r2.imgg.dev/MaaAssistantArknights/MaaAssistantArknights/releases/download/v4.23.3/MAA-v4.23.3-linux-x86_64.tar.gz"
        ]
```

**Comment by dragove** [comment]
我尝试用wget都试了一下，第三个链接可以达到 7M/s 的下载速度，第二个可以达到3M/s，第一个只有30kB/s,也不知道能不能下完。猜测是第一个链接过慢或者断连导致的？

**Comment by dragove** [comment]
我重新试了几次，最后一次正常了，或许报错的时候可以带一下链接。或者可以指定链接，然后加一个github release里的链接？感觉镜像可能没有直接从release下载快

**Comment by wangl-cc** [comment]
嗯，那我把GitHub release加到也加到测速列表里面吧，我之前是考虑到国内下载GitHub release可能会很久连接不上，所以就没把他放进去。现在如果你想直接从GitHub release下载，可以设置一个变量CI，因为我在CI里是跳过测速的。我之后加一个选项跳过测速吧。

**Comment by dragove** [comment]
好的,谢谢你啦～

**Comment by wangl-cc** [comment]
在最新版，你可以用 `maa install -t0` 来关闭测速了。
