### ISSUE TITLE
feat: 在运行时交互式输入参数

### ISSUE THREAD

**Issue by Cryolitia** [MaaAssistantArknights/maa-cli#50]
我们可否增加一项功能，通过允许在配置文件中将参数的值设置为`“Input”`，以使得`maa-cli`在读取配置时如遇到此值则在标准输入中读取外部输入配置并使用外部输入替换此值。我们相信，这项功能将减少对配置文件的频繁修改，给用户更好的使用体验。

**Comment by wangl-cc** [comment]
嗯。我确实打算打算实现像CMAKE一样通过命令行参数来改变任务里面某些值，不过交互式的也可以。

**Comment by Cryolitia** [comment]
考虑到不确定运行中有多少以及哪些参数需要手动输入，因此命令行参数可能会极度复杂。我的想法是在解析JSON过程中遇到值为"input"就从标准输入读入直到解析完成，如果想要非交互式也只需要重定向标准输入就可以了。

**Comment by wangl-cc** [comment]
两个可能用例不一样吧，我的这个想法是 `maa run <task> -T<task_type>.<param>=<values> -T...` 这样，这样是要求本身定义的Task是完整的，然后如果要改变某个任务的某一个值就重复 `-T` 来覆盖已有的参数，如果不带就按照默认的定义来运行，这样对非交互的运行比较友好。我自己的话可能会比较常用 `maa run fight -TFight.stage=<stage>` 然后每次要打别的关了就改一下对应的值，默认的话就打1-7。如果有个 `Input`，每次运行到给定地方的时候，停下来等用户输入，这样的好处是不需要一个完整的任务，可以作为一个模版。但是我觉得非交互运行的时候，如果要调整多个参数可能用起来不够优雅？可能要 `echo "<input_1>\n<input_2>\n" | maa run <task_template>`，在不对照着`<task_template>` 里面 `Input` 的上下文时候，可能很难知道每一个具体对应的是那个参数。不过我觉得这个这个功能还是不错的，这样我们就可以内置一些模版，来实现开盒即用。同时两者也不冲突，完全可以用我那种方式来在覆盖掉 `Input` 的，这样就可以非交互式的运行了。

**Comment by Cryolitia** [comment]
我指的交互式输入当然是在解析时而不是运行时，根据我的观察，maa-cli是一次性解析完所有的配置再运行的。这样用户也不需要等待运行到Fight任务再手动输入配置。

不使用命令行参数的一个考虑是，一个配置里可能有多个同类型任务，这样用命令行参数就很难指定到具体的param去override

**Comment by wangl-cc** [comment]
> 我指的交互式输入当然是在解析时而不是运行时，根据我的观察，maa-cli是一次性解析完所有的配置再运行的。这样用户也不需要等待运行到Fight任务再手动输入配置。

这个是我表述错了，确实是在解析的时候。

> 不使用命令行参数的一个考虑是，一个配置里可能有多个同类型任务，这样用命令行参数就很难指定到具体的param去override

这个我确实没考虑到可能会有多个同类型任务的情况，这样的情况下可能需要额外的index来定位，这样确实会比较麻烦。


不过我还是打算两种都实现，主要是我个人不是很喜欢在CLI里面进行交互式操作，因为没办法在Shell里面重复而且没有补全。
